- name: "Program Committee"
  venues:
    - name: "International Conference on Automated Software Engineering (ASE 2021), Technical Track"
    - name: "The Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering (ESEC/FSE2021), Technical Track"
    - name: "International Conference on Software Engineering (ICSE2020), Technical Research"
    - name: "The Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering (ESEC/FSE2020), Technical Track"
    - name: "International Conference on Automated Software Engineering (ASE 2020), Technical Track"
    - name: "International Conference on Mining Software Repositories (MSR2020), Technical Research"
    - name: "International Conference on Mining Software Repositories (MSR2020), Mining Challenge"
    - name: "International Workshop on Visualizing Software  (VISSOFT2020), Technical Program"
    - name: "International Conference on Software Analysis, Evolution, and Reengineering (SANER2020), ERA Research"
    - name: "International Conference on Mining Software Repositories (MSR2019), Technical Research"
    - name: "International Conference on Mining Software Repositories (MSR2019), Data Showcase"
    - name: "International Conference on Software Engineering (ICSE2019), Workshops"
    - name: "International Conference on Software Analysis, Evolution, and Reengineering (SANER2019), Technical Research"
    - name: "International Conference on Software Analysis, Evolution, and Reengineering (SANER2019), ERA Research"
    - name: "International Conference on Software Maintenance and Evolution (ICSME2018), Technical Research"
    - name: "International Conference on Mining Software Repositories (MSR2018), Technical Research"
    - name: "International Conference on Program Comprehension (ICPC2018), Tool Demonstration"
    - name: "International Conference on Mining Software Repositories (MSR2018), Mining Challenge"
    - name: "International Conference on Mining Software Repositories (MSR2017), Mining Challenge"
    - name: "International Conference on Software Maintenance and Evolution (ICSME2017), Technical Research"
    - name: "International Workshop on Empirical Software Engineering in Practice (IWESEP2017)"
- name: "Journal Referee"
  venues:
    - name: "ACM Transactions on Software Engineering and Methodology (TOSEM), 2019 (Distinguished Reviewer Board)"
    - name: "IEEE Transactions of Software Engineering (TSE), 2017-, Impact Factor: 3.27"
    - name: "Springer Journal of Empirical Software Engineering (EMSE), 2017-"
    - name: "Journal of Systems and Software (JSS), 2017, Impact Factor: 2.444"
- name: "Organizing Committee"
  venues:
    - name: "[Late Breaking Result Co-Chair] International Conference on Automated Software Engineering(ASE2021)"
    - name: "[Shadow Program Co-Chair] International Conference on Mining Software Repositories (MSR2021)"
    - name: "[Student Contest on Software Engineering (SCORE) Chair] International Conference on Software Engineering (ICSE2021)"
    - name: "[Special Event Chair] International Conference on Software Engineering (ICSE2020)"
    - name: "[Schedule Chair] International Conference on Automated Software Engineering(ASE2020)"
    - name: "[Industry Program Chair] International Conference on Software Engineering (ICSE2019)"
    - name: "[Registration Chair] International Workshop on Empirical Software Engineering in Practice (IWESEP2016)"
    - name: "[Financial Chair] International Workshop on Empirical Software Engineering in Practice (IWESEP2014)"
    - name: "[Financial Chair] Thailand-Japan International Academic Conference 2013 (TJIA2013)"
- name: "Award Committee"
  venues:
    - name: "Selection Committee for the Most Influential Paper Award at International Conference on Mining Software Repositories (MSR2020)"
    - name: "Selection Committee for the Distinguished Paper Award at International Conference on Software Analysis, Evolution, and Reengineering (SANER2019)"
    - name: "Selection Committee for the IEEE TCSE Distinguished Paper Award at International Conference on Software Maintenance and Evolution (ICSME2017)"
- name: "Additional Reviewer"
  venues:
    - name: "The 40th International Conference on Software Engineering (ICSE2018)"
    - name: "The 23rd Asia-Pacific Software Engineering Conference (APSEC2016)"
    - name: "The 23rd International Conference on Software Analysis, Evolution, and Reengineering (SANER2016), Tool Track"
    - name: "Thailand-Japan International Academic Conference 2013 (TJIA2013)"

- name: "Student Volunteer"
  venues:
    - name: "The 23rd International Conference on Software Analysis, Evolution, and Reengineering (SANER2016), FOSE"
